<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="shark-v1">

  <xacro:include filename="$(find shark_description)/urdf/shark.xacro" />
  <xacro:include filename="$(find sensors_description)/urdf/realsense_camera.urdf.xacro" />
  <xacro:include filename="$(find boris_head_description)/urdf/boris_head.urdf" />
  <xacro:include filename="$(find boris_head_description)/urdf/control.urdf.xacro" />

  <!-- <xacro:include filename="$(find boris_description)/ros2_control/shark_ros2_control.xacro" /> -->

  <xacro:property name="base_width" value="0.336" />
  <xacro:property name="base_len" value="0.5" />
  <xacro:property name="base_height" value="0.231" />
  <xacro:property name="wheel_radius" value="0.0825" />
  <xacro:property name="base_wheel_gap" value="0.05" />
  <xacro:property name="wheel_width" value="0.06" />
  <xacro:property name="wheel_separation" value="0.39" />
  <xacro:property name="wheel_joint_offset" value="0.0" />
  <xacro:property name="caster_height" value="0.07" />
  
  <xacro:property name="dorso_width" value="0.338" />
  <xacro:property name="dorso_len" value="0.282" />
  <xacro:property name="dorso_height" value="0.765" />
  
  <xacro:property name="arm_support_width" value="0.336" />
  <xacro:property name="arm_support_len" value="0.325" />
  <xacro:property name="arm_support_height" value="0.047" />
  <xacro:arg name="arm_z_position" default="0.34"/>
  <xacro:property name="arm_z_position" value="$(arg arm_z_position)" />

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}"
        iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0"
        izz="${2.0*m*(r*r)/5.0}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="imu" params="parent xyz rpy">
    <link name="imu_link" />
    <joint name="imu_joint" type="fixed">
      <parent link="${parent}" />
      <child link="imu_link" />
      <origin xyz="${xyz}" rpy="${rpy}" />
    </joint>
  </xacro:macro>

<<<<<<< HEAD:boris_description/urdf/boris_description.xacro
  <xacro:sick_lms_1xx name="sick" ros_topic="/scan" />
=======

  <xacro:sick_lms1xx robot_namespace="/lms1xx" />
>>>>>>> 46ae7d8 (Add caster wheel for gazebo simulation):boris_description/urdf/boris.xacro

  <xacro:macro name="dorso" params="parent depth width height xyz rpy">
    <link name="dorso_link">
      <xacro:box_inertia m="1" w="${width}" h="${height}" d="0.01" />
      <visual>
        <origin xyz="0.0 0.0 ${height/2}"/>
        <material name="lightgray" />
        <geometry>
          <box size="${depth} ${width} ${height}" />
          </geometry>
          </visual>
          <collision>
            <origin xyz="0.0 0.0 ${height/2}"/>
            <geometry>
              <box size="${depth} ${width} ${height}" />
              </geometry>
      </collision>
    </link>
    <joint name="dorso_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="dorso_link"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="arm_support" params="parent width height depth xyz rpy">
    <link name="arm_support_link">
      <xacro:box_inertia m="1" w="${width}" h="${height}" d="0.01" />
      <visual>
        <material name="lightgray" />
        <geometry>
          <box size="${depth} ${width} ${height}" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${depth} ${width} ${height}" />
        </geometry>
      </collision>
    </link>
    <joint name="arm_support_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="arm_support_link"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>
  </xacro:macro>

  
  <joint name="laser_joint" type="fixed">
    <origin xyz="${base_len/2 + 0.017 + 0.05} 0 ${0.02 + base_height/2}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="sick_mount_link" />
  </joint>

  <!-- <joint name="dorso_head" type="fixed">
    <parent link="dorso_link" />
    <child link="head_root" />
    <origin xyz="0 0 ${dorso_height + 0.04}" rpy="0 0 0" />
  </joint> -->

<<<<<<< HEAD:boris_description/urdf/boris_description.xacro
  <!-- <joint name="arm_to_robot" type="fixed">
    <origin xyz="0.1 0 ${arm_support_height/2}" rpy="0 0 0"/>
    <parent link="arm_support_link"/>
    <child link="wx200/base_link"/>
  </joint> -->

    <xacro:macro name="imu" params="parent xyz rpy">
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="imu_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>
    </xacro:macro>

  <xacro:realsense_camera name="camera" parent="dorso_link" xyz="${dorso_len/2 + 0.05} 0 ${dorso_height + 0.053}" rpy="0 0 0"/>
=======
  <xacro:realsense_camera name="camera" parent="dorso_link">
    <origin xyz="${dorso_len/2 + 0.05} 0 ${dorso_height + 0.053}" rpy="0 0 ${3.14/8}" />
  </xacro:realsense_camera>
  <xacro:realsense_gazebo />
  <xacro:add_optical_frame name="camera_link" />
>>>>>>> 46ae7d8 (Add caster wheel for gazebo simulation):boris_description/urdf/boris.xacro

  <xacro:dorso parent="base_link" depth="${dorso_len}" width="${dorso_width}" height="${dorso_height}" xyz="${-base_len/2 + (dorso_len/2)} 0 ${base_height/2}" rpy="0 0 0"/>
  <xacro:arm_support parent="dorso_link" width="${arm_support_width}" height="${arm_support_height}" depth="${arm_support_len}" xyz="${dorso_len/2 + arm_support_len/2} 0 ${arm_z_position}" rpy="0 0 0"/>
  <xacro:sensor_hokuyo parent="base_link" xyz="${base_len/2 + 0.017 + 0.024} 0 ${0.02 - base_height/2}" rpy="3.14 0 0" name="ground"/>
  <xacro:sensor_hokuyo parent="base_link" xyz="${-base_len/2 - 0.017 - 0.024} 0 ${0.02 - base_height/2}" rpy="3.14 0 3.14" name="back"/>
<<<<<<< HEAD:boris_description/urdf/boris_description.xacro
  <!-- <xacro:imu parent="base_link" xyz="-0.01 0 ${0.02 - base_height/2}" rpy="-0.014161 -0.0203861 0" /> -->
  <!-- <xacro:boris_arm parent="arm_support_link" xyz="0.1 0 ${arm_support_height/2}" rpy="0 0 0"/> -->
  <!-- <xacro:rgb_cam parent="wx200/gripper_bar_link" name="webcam" xyz="-0.078 0.0 0.05" rpy="0 0 0"/> -->
  <xacro:imu parent="base_link" xyz="${base_len/2 + 0.0625} 0 ${0.02 - base_height/2}" rpy="0 0 0"/>
  <xacro:shark_base/>  <!-- isso aq n existe mais, a gente reverteu as mudanÃ§as do luis que transformavam aquilo tudo em um macro q n ta aparecendo mais -->
</robot>
=======
  <xacro:imu parent="base_link" xyz="-0.01 0 ${0.02 - base_height/2}" rpy="-0.014161 -0.0203861 0" />

  <gazebo reference="dorso_link">
    <material>Gazebo/DarkGray</material>
  </gazebo>

  <gazebo reference="arm_support_link">
    <material>Gazebo/DarkGray</material>
  </gazebo>
</robot>
>>>>>>> 46ae7d8 (Add caster wheel for gazebo simulation):boris_description/urdf/boris.xacro
