/head:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      #joint_state_broadcaster:
        #type: joint_state_broadcaster/JointStateBroadcaster
      camera_controller:
        type: joint_trajectory_controller/JointTrajectoryController
  camera_controller:
    ros__parameters:
      joints:
        - head_pan_joint
        - head_tilt_joint
      interface_name: position
      command_interfaces:
        - position
      state_interfaces:
        - position
