doris_head:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  horizontal_neck_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: horizontal_neck_joint
    pid: {p: 100.0, i: 1.0, d: 1.0}
  vertical_neck_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: vertical_neck_joint
    pid: {p: 100.0, i: 1.0, d: 1.0}
  jaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: jaw_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  right_vertical_eyebrow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_vertical_eyebrow_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  left_vertical_eyebrow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_vertical_eyebrow_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  right_rotacional_eyebrow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_rotacional_eyebrow_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  left_rotacional_eyebrow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_rotacional_eyebrow_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  right_superior_eyelid_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_superior_eyelid_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  left_superior_eyelid_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_superior_eyelid_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  right_inferior_eyelid_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_inferior_eyelid_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  left_inferior_eyelid_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_inferior_eyelid_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  right_eye_horizontal_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_eye_horizontal_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  left_eye_horizontal_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_eye_horizontal_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  right_eye_vertical_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_eye_vertical_joint
    pid: {p: 10.0, i: 1.0, d: 1.0}
  left_eye_vertical_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_eye_vertical_joint
    pid: {p: 10.0 , i: 1.0, d: 1.0}
  


