/head:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      #joint_state_broadcaster:
        #type: joint_state_broadcaster/JointStateBroadcaster
      neck_controller:
        type: joint_trajectory_controller/JointTrajectoryController
  neck_controller:
    ros__parameters:
      joints:
        - horizontal_neck_joint
        - vertical_neck_joint
      interface_name: position
      command_interfaces:
        - position
      state_interfaces:
        - position
  joint_state_broadcaster:
    ros__parameters:
      joints:
        joints:
        - horizontal_neck_joint
        - vertical_neck_joint
